title: Rômulo Filho # your name (or website title) here
logo: "/assets/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Hello! I'm Rômulo Filho, a Data Scientist from Fortaleza, CE - Brazil. I'm passionate about games, technology and music. 
 This is my portfolio where you will find links to the papers I published, talks I presented and some other interesting stuff.
 Hope you enjoy it!
 <br><br>
 <a href="https://www.linkedin.com/in/romulofff/">View My LinkedIn Profile</a> 

author:
  name: "Rômulo Férrer Filho"
  avatar: "/assets/images/me.jpg"
  location: "Fortaleza, BR"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/romulofff"
# twitter_username: romulof27
# github_username:  romulofff

 
theme: jekyll-theme-minimal
google_analytics: G-9R08KHY15V # your Google Analytics tracking ID here
